- name: Create Django data directory
  file:
    state: directory
    dest: /srv/django
    owner: root
    group: root
    mode: 0755
- name: Install PostgreSQL server
  apt: package={{ item }} state=present force=yes
  with_items:
    - postgresql
    - python-psycopg2
- name: Remove the default PostgreSQL cluster
  command: /usr/bin/pg_dropcluster --stop "{{ pg_version }}" main
  args:
    removes: "/etc/postgresql/{{ pg_version }}/main"
- name: Create a new PostgreSQL cluster
  command: /usr/bin/pg_createcluster -d /srv/django/postgres --locale=en_AU.utf8 "{{ pg_version }}" django
  args:
    creates: "/etc/postgresql/{{ pg_version }}/django"
- name: PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true
- name: Configure PostgreSQL
  template:
    src: postgresql.conf
    dest: "/etc/postgresql/{{ pg_version }}/django/postgresql.conf"
    owner: root
    group: root
    mode: 0644
  notify: start_django_pg_cluster
- name: Configure PostgreSQL authentication
  copy:
    src: pg_hba.conf
    dest: "/etc/postgresql/{{ pg_version }}/django/pg_hba.conf"
    owner: root
    group: root
    mode: 0644
  notify: start_django_pg_cluster
- meta: flush_handlers
