vhost: "www.{{ ansible_domain }} {{ ansible_domain }}"
workers: 3
threads: 12
db_password: '1234567890'
debug: false
docker_image: docker.pkg.github.com/thepointchurch/thepoint/thepoint:latest
backup_bucket: ''
email_backend: django_sendmail_backend.backends.EmailBackend
cache_timeout: 300
cache_url: 'dummycache://'
cache_ops: false
log_group: thepoint
frontend_nets: []
cron: true
