---
- hosts: tag_Role_thepoint_docker
  become: yes
  pre_tasks:
    - name: Gathering EC2 Facts
      action: amazon.aws.ec2_metadata_facts
  roles:
    - aws
    - common
    - docker

    # Test website

    - test:
      role: thepoint_website
      shortname: test
      description: The Point Test
      vhost: test.thepoint.org.au
      debug: true
      cron: false
      workers: 1
      threads: 2
      secret_key: "{{ test_secret_key }}"
      static_bucket: static-test.thepoint.org.au
      media_bucket: thepoint-media-test
      docker_image: ghcr.io/thepointchurch/thepoint/thepoint:testing
      email_backend: django.core.mail.backends.console.EmailBackend
      log_group: "{{ cw_group_test }}"

    # Production website

    - prod:
      role: thepoint_website
      shortname: prod
      description: The Point
      vhost: thepoint.org.au www.thepoint.org.au
      secret_key: "{{ prod_secret_key }}"
      cache_url: redis://cache_prod:6379
      cache_timeout: 21600
      cache_ops: true
      static_bucket: static.thepoint.org.au
      media_bucket: thepoint-media
      backup_bucket: thepoint-backup
      log_group: "{{ cw_group_prod }}"
      email_backend: django_amazon_ses.EmailBackend

    - nginx:
      role: docker_nginx
      log_group: "{{ cw_group_prod }}"
    - runner:
      role: docker_runner
      log_group: "{{ cw_group_prod }}"
