---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:

    # Utility buckets

    - thepoint-backup:
      role: s3_storage
      bucket: thepoint-backup
      bucket_tags:
        type: backup
        website: thepoint
      versioning: true
      transition_days: 30
      noncurrent_version_transition_days: 30
      noncurrent_version_expiration_days: 365
      region: eu-north-1

    # Production buckets

    - static.thepoint.org.au:
      role: s3_storage
      bucket: static.thepoint.org.au
      public: true
      bucket_tags:
        type: website
        website: thepoint
    - media.thepoint.org.au:
      role: s3_storage
      bucket: thepoint-media
      bucket_tags:
        type: website
        website: thepoint
      versioning: true
      noncurrent_version_transition_days: 30
      noncurrent_version_expiration_days: 60

    # Test buckets

    - static-test.thepoint.org.au:
      role: s3_storage
      bucket: static-test.thepoint.org.au
      public: true
      bucket_tags:
        type: website
        website: thepoint
    - media-test.thepoint.org.au:
      role: s3_storage
      bucket: thepoint-media-test
      bucket_tags:
        type: website
        website: thepoint
      versioning: true
      noncurrent_version_transition_days: 30
      noncurrent_version_expiration_days: 60

    # Production/test VM

    - thepoint_docker:
      role: thepoint_ec2
      hostname: junia.thepoint.org.au
      instance_role: thepoint_docker
