- hosts: tag_Role_thepoint_docker
  become: yes
  pre_tasks:
    - name: Gathering EC2 Facts
      action: ec2_metadata_facts
  roles:
    - aws
    - common
    - docker

# Test website

    - test:
      name: thepoint_website
      shortname: test
      description: The Point Test
      vhost: test.thepoint.org.au
      debug: true
      cron: false
      workers: 1
      threads: 2
      secret_key: "{{ test_secret_key }}"
      static_bucket: static-test.thepoint.org.au
      media_bucket: media-test.thepoint.org.au
      backup_bucket: thepoint-backup
      docker_image: docker.pkg.github.com/thepointchurch/thepoint/thepoint:testing
      email_backend: django.core.mail.backends.console.EmailBackend
      log_group: "{{ cw_group_test }}"

# Production website

    - prod:
      name: thepoint_website
      shortname: prod
      description: The Point
      vhost: thepoint.org.au www.thepoint.org.au
      secret_key: "{{ prod_secret_key }}"
      static_bucket: static.thepoint.org.au
      media_bucket: media.thepoint.org.au
      backup_bucket: thepoint-backup
      log_group: "{{ cw_group_prod }}"

    - nginx:
      name: docker_nginx
      log_group: "{{ cw_group_prod }}"
    - runner:
      name: docker_runner
      log_group: "{{ cw_group_prod }}"
