---
- hosts: tag_Role_thepoint_docker
  become: yes
  pre_tasks:
    - name: Gathering EC2 Facts
      action: amazon.aws.ec2_metadata_facts
  roles:
    - aws
    - common
    - docker

    # Test website

    - thepoint_website_test:
      role: thepoint_website
      thepoint_website_shortname: test
      thepoint_website_description: The Point Test
      thepoint_website_vhost: test.thepoint.org.au
      thepoint_website_debug: true
      thepoint_website_cron: false
      thepoint_website_workers: 1
      thepoint_website_threads: 2
      thepoint_website_secret_key: "{{ test_secret_key }}"
      thepoint_website_static_bucket: static-test.thepoint.org.au
      thepoint_website_media_bucket: thepoint-media-test
      thepoint_website_docker_image: thepointchurch/thepoint:testing
      thepoint_website_email_backend: django.core.mail.backends.console.EmailBackend
      thepoint_website_log_group: "{{ cw_group_test }}"

    # Production website

    - thepoint_website_prod:
      role: thepoint_website
      thepoint_website_shortname: prod
      thepoint_website_description: The Point
      thepoint_website_vhost: thepoint.org.au www.thepoint.org.au
      thepoint_website_secret_key: "{{ prod_secret_key }}"
      thepoint_website_cache_url: redis://cache_prod:6379
      thepoint_website_cache_timeout: 21600
      thepoint_website_cache_ops: true
      thepoint_website_static_bucket: static.thepoint.org.au
      thepoint_website_media_bucket: thepoint-media
      thepoint_website_backup_bucket: thepoint-backup
      thepoint_website_log_group: "{{ cw_group_prod }}"
      thepoint_website_email_backend: django_amazon_ses.EmailBackend

    - docker_nginx_instance:
      role: docker_nginx
      docker_nginx_log_group: "{{ cw_group_prod }}"
    - docker_runner_instance:
      role: docker_runner
      docker_runner_log_group: "{{ cw_group_prod }}"
