---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:

    # Utility buckets

    - s3_storage_backup:
      role: s3_storage
      s3_storage_bucket: thepoint-backup
      s3_storage_bucket_tags:
        type: backup
        website: thepoint
      s3_storage_versioning: true
      s3_storage_transition_days: 30
      s3_storage_noncurrent_version_transition_days: 30
      s3_storage_noncurrent_version_expiration_days: 365
      s3_storage_region: eu-north-1

    # Production buckets

    - s3_storage_static:
      role: s3_storage
      s3_storage_bucket: static.thepoint.org.au
      s3_storage_public: true
      s3_storage_encryption: AES256
      s3_storage_bucket_key_enabled: true
      s3_storage_bucket_tags:
        type: website
        website: thepoint
    - s3_storage_media:
      role: s3_storage
      s3_storage_bucket: thepoint-media
      s3_storage_bucket_tags:
        type: website
        website: thepoint
      s3_storage_versioning: true
      s3_storage_noncurrent_version_transition_days: 30
      s3_storage_noncurrent_version_expiration_days: 60

    # Test buckets

    - s3_storage_static_test:
      role: s3_storage
      s3_storage_bucket: static-test.thepoint.org.au
      s3_storage_public: true
      s3_storage_encryption: AES256
      s3_storage_bucket_key_enabled: true
      s3_storage_bucket_tags:
        type: website
        website: thepoint
    - s3_storage_media_test:
      role: s3_storage
      s3_storage_bucket: thepoint-media-test
      s3_storage_bucket_tags:
        type: website
        website: thepoint
      s3_storage_versioning: true
      s3_storage_noncurrent_version_transition_days: 30
      s3_storage_noncurrent_version_expiration_days: 60

    # Production/test VM

    - thepoint_ec2_docker:
      role: thepoint_ec2
      thepoint_ec2_hostname: junia.thepoint.org.au
      thepoint_ec2_instance_role: thepoint_docker
