- name: "Django {{ shortname }} collectstatic"
  command: docker exec "django_{{ shortname }}" upperroom collectstatic --no-input
- name: "Django {{ shortname }} migrate"
  command: docker exec "django_{{ shortname }}" upperroom migrate --no-input
