---
- name: "Django collectstatic {{ shortname }}"
  ansible.builtin.command: docker exec "django_{{ shortname }}" upperroom collectstatic --no-input
  changed_when: false
- name: "Django migrate {{ shortname }}"
  ansible.builtin.command: docker exec "django_{{ shortname }}" upperroom migrate --no-input
  changed_when: false
