- name: "Django {{ shortname }} collectstatic"
  command: docker exec "django_{{ shortname }}" thepoint collectstatic --no-input
- name: "Django {{ shortname }} migrate"
  command: docker exec "django_{{ shortname }}" thepoint migrate --no-input
