- name: "Django {{ shortname }} collectstatic"
  command: docker exec "django_{{ shortname }}" thepoint-manage collectstatic --no-input
- name: "Django {{ shortname }} migrate"
  command: docker exec "django_{{ shortname }}" thepoint-manage migrate --no-input
