---
- name: newaliases
  ansible.builtin.command: /usr/bin/newaliases
  changed_when: false
- name: update-exim4
  ansible.builtin.command: /usr/sbin/update-exim4.conf
  changed_when: false
- name: reload_exim
  ansible.builtin.service:
    name: exim4
    state: reloaded
- name: reload_chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
- name: reload_rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
- name: reload_journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
