- name: newaliases
  command: /usr/bin/newaliases
- name: update-exim4
  command: /usr/sbin/update-exim4.conf
- name: reload_exim
  service:
    name: exim4
    state: reloaded
- name: reload_chrony
  service:
    name: chrony
    state: restarted
- name: reload_rsyslog
  service:
    name: rsyslog
    state: restarted
