- name: reload_nginx
  service:
    name: nginx
    state: reloaded
- name: restart_nginx
  service:
    name: nginx
    state: restarted
- name: reload_rsyslog
  shell: "/bin/kill -SIGHUP $(cat /var/run/rsyslogd.pid)"
