---
- name: Set the locale to en_AU.UTF-8
  community.general.locale_gen:
    name: en_AU.UTF-8
    state: present
- name: Set the timezone to Australia/Brisbane
  community.general.timezone:
    name: Australia/Brisbane
- name: Install miscellaneous packages
  ansible.builtin.apt:
    pkg:
      - acl
      - aptitude
      - dnsutils
      - git
      - net-tools
      - python-is-python3
    state: present
    force: yes
- name: Install unattended upgrades
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    state: present
    force: yes
- name: Configure unattended upgrades (periodic)
  ansible.builtin.copy:
    src: unattend/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
- name: Configure unattended upgrades
  ansible.builtin.template:
    src: unattend/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
- name: Configure journald
  ansible.builtin.template:
    src: systemd/journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_journald
- name: Install chrony
  ansible.builtin.apt:
    pkg:
      - chrony
    state: present
    force: yes
- name: Configure chrony
  ansible.builtin.template:
    src: chrony/chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_chrony
- name: Install Exim
  ansible.builtin.apt:
    pkg:
      - exim4-daemon-light
    state: present
    force: yes
- name: Configure root mail
  when: root_mail is defined
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/aliases
    mode: 0644
    line: 'root: {{ root_mail }}'
    regexp: '^root: '
  notify: newaliases
- name: Configure root mail
  when: root_from is defined
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/email-addresses
    mode: 0644
    line: 'root: {{ root_from }}'
    regexp: '^root: '
- name: Configure Exim
  ansible.builtin.template:
    src: exim/update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - update-exim4
    - reload_exim
- name: Configure Exim credentials
  when:
    - smtp_user is defined
    - smtp_password is defined
  ansible.builtin.template:
    src: exim/passwd.client
    dest: /etc/exim4/passwd.client
    owner: root
    group: root
    mode: 0644
- name: Configure Syslog format
  ansible.builtin.lineinfile:
    state: present
    create: yes
    dest: /etc/rsyslog.d/00-rfc3339.conf
    mode: 0644
    line: '$ActionFileDefaultTemplate RSYSLOG_FileFormat'
    regexp: '^\$ActionFileDefaultTemplate '
  notify: reload_rsyslog
- name: Format Filesystems
  community.general.filesystem:
    fstype: ext4
    dev: /dev/{{ item.key }}
  with_dict: "{{ filesystems }}"
- name: Mount Filesystems
  ansible.posix.mount:
    state: mounted
    src: /dev/{{ item.key }}
    name: '{{ item.value }}'
    fstype: ext4
    opts: noatime
    passno: 2
  with_dict: "{{ filesystems }}"
